version: "3.3"
services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.lb
    networks:
      app_net:
        ipv4_address: 172.16.238.2
    environment:
      SERVERADDR: "172.16.238.3:5001,172.16.238.4:5001,172.16.238.3:5001" 


  server-1:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      app_net:
        ipv4_address: 172.16.238.3
  
  server-2:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      app_net:
        ipv4_address: 172.16.238.4

  server-3:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      app_net:
        ipv4_address: 172.16.238.5


  client-1:
    depends_on:
      - loadbalancer
    networks:
      app_net:
        ipv4_address: 172.16.238.6
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVERADDR: "172.16.238.2:5000" 

  client-2:
    depends_on:
      - loadbalancer
    networks:
      app_net:
        ipv4_address: 172.16.238.7
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVERADDR: "loadbalancer:5000" 

  client-3:
    depends_on:
      - loadbalancer
    networks:
      app_net:
        ipv4_address: 172.16.238.8
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVERADDR: "loadbalancer:5000" 

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
  data: